apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-btq4
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-btq4
    app.kubernetes.io/part-of: ci1t-830-0089-app
  name: devfile-sample-btq4
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-btq4
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-btq4
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-830-0089-tenant/ci1t-830-0089-app/devfile-sample-btq4@sha256:471f92ea3bfa23e0ca10bff4a5012b1ef1acee478835923bd18472c7b593b22a
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
